### PR TITLE
Fix travis 'unsatisfiable' conda error

### PR DESCRIPTION
**Pull request by etgalloway**
Fix for #357.

Replaces conda part of `.travis.yml` with corresponding part of http://conda.pydata.org/docs/travis.html#the-travis-yml-file. Removes `sudo: false`.

### CODE REVIEW

**Comment by aflaxman** [comment]
Thanks @etgalloway , When the checks finish I'll merge.  Do you want to be added as a contributor to this project?  It seems like you are the main force behind recent updates.

**Comment by etgalloway** [comment]
@aflaxman I'd be honored to be added :smile:.

**Comment by aflaxman** [comment]
Next question is how do I add you? :)  @jakevdp you might be the only one with the power to add people at this point.

**Comment by jakevdp** [comment]
I added @etgalloway as a collaborator, and made @aflaxman an admin :smile:
Thanks for all your work here!

**Comment by aflaxman** [comment]
Thanks @jakevdp . No good deed goes unpunished, huh?

**Comment by etgalloway** [comment]
Thanks @jakevdp.

**Pull request merged**
