### PR TITLE
json serializer for numpy

### PR DESCRIPTION
**Pull request by vasseur**
in reference to issue #193

### CODE REVIEW

**Comment by fabianegli** [comment]
How is this not yet in the code base? This is bugging me again and again. The fix was proposed more than a year ago in [this answer](https://github.com/mpld3/mpld3/issues/193#issuecomment-339962876) to issue #193. Later in the same issue, @chytrik even posted a [fix](https://github.com/mpld3/mpld3/issues/193#issuecomment-450514746). 

Would it be accepted if these two lines would be added in a pull request?

**Comment by cliffckerr** [comment]
I understand your frustration -- we
      should be a couple weeks away from releasing a new official
      version, but in the mean time, please check out the fork
      http://github.com/sciris/mpld3 and see if the issue is already
      fixed there.
      
      On 7/3/19 5:46 PM, Fabian Egli wrote:
    
    
      
      How is this not yet in the code base? This is bugging me again
        and again. The fix was proposed more than a year ago in this answer to issue #193. Later in the same issue, @chytrik
        even posted a fix.
      Would it be accepted if these two lines would be added in a
        pull request?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mpld3/mpld3/pull/213?email_source=notifications\u0026email_token=AAYW2WH4VNO3AQ3IEYZCIG3P5RROXA5CNFSM4AQXNV2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZDXYEA#issuecomment-508001296",
"url": "https://github.com/mpld3/mpld3/pull/213?email_source=notifications\u0026email_token=AAYW2WH4VNO3AQ3IEYZCIG3P5RROXA5CNFSM4AQXNV2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZDXYEA#issuecomment-508001296",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fabianegli** [comment]
@cliffckerr Thank you for this reply. I deleted my previous post because I immediately realized the two lines fixing this issue were already in the codebase - but just not yet in a release. I am looking forward to the next release.

BTW: Because the fix was already merged, installing from the official mpld3 git repository worked for me ()

`pip install "git+https://github.com/mpld3/mpld3"`

**Comment by cliffckerr** [comment]
@fabianegli Ah, got it -- sorry for the miscommunication!

**Comment by fabianegli** [comment]
This commit fixed the issue:  https://github.com/mpld3/mpld3/commit/41746d12a773187e16f2bc9930f8462ba68632b3

**Pull request merged**
